pets/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, re_path, include
from .views import *
from rest_framework import routers

router = routers.SimpleRouter()
router.register(r'api/v1/articles', APIArticle, basename='article')


urlpatterns = [
    path('', MainPage.as_view(), name='home'),
    path('cats/', CatsPage.as_view(), name='cats'),
    path('dogs/', DogsPage.as_view(), name='dogs'),
    path('add-post', login_required(AddPost.as_view()), name='add-post'),
    path('join/', JoinPage.as_view(), name='join'),
    path('sign-in/', LoginUser.as_view(), name='sign-in'),
    path('sign-out/', logout_user, name='sign-out'),
    path('search/', search_page, name='search'),
    path('terms-of-service/', TermsPage.as_view(), name='terms'),
    path('comment/', comment_receiver, name='add_comment'),
    path('contact/', ContactPage.as_view(), name='contact'),
    path('contact-receiver/', contact_receiver, name='contact_receiver'),
    path('<slug:post_slug>/', ShowPost.as_view(), name='post'),
    path('api/v1/auth/', include('djoser.urls')),
    re_path(r'^auth/', include('djoser.urls.authtoken')),
]
urlpatterns += router.urls

wild/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from pets.views import page_not
from .settings import MEDIA_URL, DEBUG, MEDIA_ROOT
from django.conf.urls import handler404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pets.urls')),
]
if DEBUG:
    urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

handler500 = page_not

pets/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


class Article(models.Model):
    title = models.CharField(max_length=255, verbose_name='Title', null=True)
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name='URL')
    content = models.TextField(blank=True, verbose_name='Article text')
    photo = models.CharField(max_length=300, verbose_name='Photo')
    time_create = models.DateTimeField(auto_now_add=True, verbose_name='Time create')
    time_update = models.DateTimeField(auto_now=True, verbose_name='Time update')
    is_published = models.BooleanField(default=False, verbose_name='Is published')
    cat = models.ForeignKey('Category', on_delete=models.CASCADE, verbose_name='Category')
    author = models.ForeignKey('auth.User', related_name='snippets', on_delete=models.CASCADE)

    class Meta:
        ordering = ['-time_create', 'title']

    def get_absolute_url(self):
        return reverse('post', kwargs={'post_slug': self.slug})

    def __str__(self):
        return self.title


class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True, verbose_name='Category')
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name='URL')

    def __str__(self):
        return self.name


class Comment(models.Model):
    article = models.ForeignKey('Article', on_delete=models.CASCADE, verbose_name='article')
    name = models.ForeignKey(User, on_delete=models.CASCADE)
    creat_date = models.DateTimeField(auto_now_add=True, verbose_name='comment_created')
    body = models.TextField(blank=True, verbose_name='comment_body')

    class Meta:
        ordering = ['creat_date']

    def __str__(self):
        return f'{self.body}'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)


class Contact(models.Model):
    name = models.CharField(max_length=250, blank=False, verbose_name='contact_name')
    email = models.EmailField(max_length=250, blank=False, verbose_name='contact_email')
    msg = models.TextField(max_length=5000, blank=False, verbose_name='contact_msg')

pets/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from .models import *


class LoginTest(forms.Form):
    name = forms.CharField(label='Username', max_length=30)
    password = forms.CharField(label='Password', widget=forms.PasswordInput({'class': 'form-input'}))


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Login', widget=forms.TextInput)
    email = forms.EmailField(label='Email', widget=forms.EmailInput)
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('article', 'name', 'body')


class ContactForm(forms.ModelForm):

    class Meta:
        model = Contact
        fields = ('name', 'email', 'msg')


class AddPostForm(forms.ModelForm):
    photo = forms.URLField(label='Photo', widget=forms.URLInput)
    content = forms.CharField(label='Your Post', widget=forms.TextInput({'class': 'textarea'}))

    class Meta:
        model = Article
        fields = ('title',  'photo', 'cat', 'content',)

pets/templates/templates/add-article.html
{% extends 'templates/base.html' %}
{% block content %}
<div class="container">
      <h1>Add post</h1>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="registerbtn">Post</button>
<!---->
</form>
</div>
{% endblock content %}

pets/templates/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link type="text/css" href="{% static 'pet_blog/css/styles.css' %}" rel="stylesheet">
    <link rel="icon" type="image/x-icon" href="{% static 'pet_blog/images/favicon.ico' %}">
</head>
<body>
<div class="header" id="myHeader">
    <ul class="mainmenu">
        {% if request.user.is_authenticated %}
            {% for m in menu|slice:"2:" %}
                    {% if m.name == 'Pets Life' %}
                        <li class="first"><a href="{% url 'home' %}">{{ m.name }}</a></li>
                    {% else %}
                    <li><a href="{% url m.url_name %}">{{ m.name }}</a></li>
                    {% endif %}
            {% endfor %}
        {% else %}
            {% for m in menu %}
                {% if m.name == 'Pets Life' %}
                    <li class="first"><a href="{% url 'home' %}">{{ m.name }}</a></li>
                {% elif m.name == 'Logout' %}
                {% elif m.name == 'Add Post' %}
                {% else %}
                    <li><a href="{% url m.url_name %}">{{ m.name }}</a></li>
                {% endif %}
            {% endfor %}
        {% endif %}
    </ul>
</div>
{% block content %}
{% endblock content %}
<div class="footer">
    <ul class="footer" >
        {% for f in footer %}
            <li><a style="color: white;" href="{% url f.url_name %}">{{ f.name }}</a></li>
        {% endfor %}
    </ul>
</div>
<script>
window.onscroll = function() {myFunction()};

var header = document.getElementById("myHeader");
var sticky = header.offsetTop;

function myFunction() {
  if (window.pageYOffset > sticky) {
    header.classList.add("sticky");
  } else {
    header.classList.remove("sticky");
  }
}
</script>
</body>
</html>

pets/templates/templates/cats.html
{% extends 'templates/base.html' %}
{% block content %}
<title>{{ title }}</title>

<div class="content-text">
    <ul class="list-articles">
        {% for post in object_list %}
            <li>
                <div>
                    <div class="art_block">
                    <p id="article_header"><a style="color: black;" href="{{ post.get_absolute_url }}">{{ post.title }}</a></p>
                    <div style="height: 150px;">
                    <p><img id="img-article-left" src="{{ post.photo }}">
                    {% autoescape off %}
                    <p>{{ post.content|truncatewords:45 }}</p>
                    {% endautoescape %}
                    </div>
                    </div>
                    <div class="article_post">
                        <p style="display: inline; float: left; margin-top: -10px; margin-bottom: 5px; color: white;">{{ post.time_create.date }}</p>
                        <p style="display: inline; float: right; margin-top: -10px; margin-bottom: 5px;"><a class="article_link" href="{{ post.get_absolute_url }}">Read Post</a></p>
                    </div>
                </div>
            </li>
        {% endfor %}
    </ul>
</div>
{% if page_obj.has_other_pages %}
<nav style="text-align: center; font-size: 30px;">
    <ul style="display: inline-flex; list-style: none;">
        {% if page_obj.has_previous %}
        <li>
            <a style="font-size: 20px;" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        </li>
        {% endif %}
        {% for pag in paginator.page_range %}
        {% if page_obj.number == pag %}
        <li style="padding-left: 5px; padding-right: 5px;">{{ pag }}</li>
        {% elif pag >= page_obj.number|add:-2 and pag <= page_obj.number|add:2 %}
        <li style="padding-left: 5px; padding-right: 5px;">
            <a href="?page={{ pag }}">{{ pag }}</a>
        </li>
        {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <li>
                <a style="font-size: 20px;" href="?page={{ page_obj.next_page_number }}">Next</a>
            </li>
        {% endif %}
    </ul>
</nav>
{% endif %}
{% endblock content %}

pets/templates/templates/contact.html
{% extends 'templates/base.html' %}

{% block content %}
<title>{{ title }}</title>
<div class="container">
  <form action="{% url 'contact_receiver' %}" method="post">
    {% csrf_token %}

    <label for="id_name">Name</label>
    <input type="text" name="name" maxlength="250" required id="id_name" placeholder="Your name..">

    <label for="id_email">Email</label>
    <input type="email" name="email" maxlength="250" required id="id_email" placeholder="Your email..">

    <label style="margin-top: 150px;" for="id_msg">Subject</label>
    <br>
    <textarea class="textarea" id="id_msg" name="msg" maxlength="5000" required placeholder="Write something.." ></textarea>

    <input class="registerbtn" type="submit" value="Submit">

  </form>
</div>
{% endblock %}

pets/templates/templates/dogs.html
{% extends 'templates/base.html' %}
{% block content %}
<title>{{ title }}</title>

<div class="content-text">
    <ul class="list-articles">
        {% for post in object_list %}
            <li>
                <div>
                    <div class="art_block">
                    <p id="article_header"><a style="color: black;" href="{{ post.get_absolute_url }}">{{ post.title }}</a></p>
                    <div style="height: 150px;">
                    <p><img id="img-article-left" src="{{ post.photo }}">
                    {% autoescape off %}
                    <p>{{ post.content|truncatewords:45 }}</p>
                    {% endautoescape %}
                    </div>
                    </div>
                    <div class="article_post">
                        <p style="display: inline; float: left; margin-top: -10px; margin-bottom: 5px; color: white;">{{ post.time_create.date }}</p>
                        <p style="display: inline; float: right; margin-top: -10px; margin-bottom: 5px;"><a class="article_link" href="{{ post.get_absolute_url }}">Read Post</a></p>
                    </div>
                </div>
            </li>
        {% endfor %}
    </ul>
</div>
{% if page_obj.has_other_pages %}
<nav style="text-align: center; font-size: 30px;">
    <ul style="display: inline-flex; list-style: none;">
        {% if page_obj.has_previous %}
        <li>
            <a style="font-size: 20px;" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        </li>
        {% endif %}
        {% for pag in paginator.page_range %}
        {% if page_obj.number == pag %}
        <li style="padding-left: 5px; padding-right: 5px;">{{ pag }}</li>
        {% elif pag >= page_obj.number|add:-2 and pag <= page_obj.number|add:2 %}
        {#{% else %}#}
        <li style="padding-left: 5px; padding-right: 5px;">
            <a href="?page={{ pag }}">{{ pag }}</a>
        </li>
        {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <li>
                <a style="font-size: 20px;" href="?page={{ page_obj.next_page_number }}">Next</a>
            </li>
        {% endif %}
    </ul>
</nav>
{% endif %}
{% endblock content %}

pets/templates/templates/index.html
{% extends 'templates/base.html' %}
{% load static %}
{% block content %}
<title>Pets Life</title>

<table bgcolor="#EFF0F2">
<thead>
  <tr id="tr">
    <td align="center" width="50%" style="margin-right: 0px;">
        <h1>Website about cats and dogs</h1>
        <img width="900" height="600" src="{% static 'pet_blog/images/main_page.jpg' %}">
    </td>
    <td width="40%" align="left">
        <div style="margin-left: 0px;">
            <ul class="latest_articles">
                <h2>Latest News</h2>
                {% for lat in latest_articles %}
                <li style="margin-top: 20px; font-size: 20px"><a href="{{ lat.get_absolute_url }}">{{ lat.title }}</a></li>
                <p style="margin-top: 3px; margin-bottom: 0px;">Date: {{ lat.time_create.date }}</p>
                <hr style="background-color: #6495ED; height: 2px; width: 60%; margin-left: 0px;">
                {% endfor %}
        </ul>
        </div>
    </td>
  </tr>
</thead>
</table>
{% endblock %}

pets/templates/templates/login.html
{% extends 'templates/base.html' %}

{% block content %}
<title>{{ title }}</title>

<div class="container">
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button class="registerbtn" type="submit">Login</button>
</form>
</div>

{% endblock content %}

pets/templates/templates/post.html
{% extends 'templates/base.html' %}
{% block content %}
<title>{{ article.title }}</title>
<div class="article">
    <h1>{{ article.title }}</h1>
    <img width="850" height="500" src="{{ article.photo }}">
    {% autoescape off %}
        {{ article.content }}
    {% endautoescape %}
</div>

<div class="article">
    {% for comment in comments %}
    <div>
        <p class="comment-name">{{ comment.name }}</p>
        <p class="comment-body">{{ comment.body }}</p>
    </div>
    {% endfor %}

{% if request.user.is_authenticated %}

    <form action="{% url 'add_comment' %}" method="post" >
        {% csrf_token %}
        <label for="body">Leave a comment...</label>
        <br>
        <textarea class="textarea" id="body" name="body"></textarea>
        <input type="hidden" id="name" name="name" value="{{ request.user.id }}">
        <input type="hidden" id="article" name="article" value="{{ article.id }}">
        <br>
        <input class="registerbtn" type="submit">
    </form>
{% else %}
    <p>Please <a href="{% url 'login' %}">Login</a> to leave comments...</p>
{% endif %}
</div>


{% endblock content %}

pets/templates/templates/register.html
{% extends 'templates/base.html' %}

{% block content %}
<title>{{ title }}</title>

<div class="container">
  <h1>Registration</h1>
  <form method="post">
  {% csrf_token %}
  {% for f in form %}
    <p><label for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
    <div>{{ f.errors }}</div>
  {% endfor %}
  <button class="registerbtn" type="submit">Registration</button>
</form>
</div>
{% endblock content %}

pets/templates/templates/search.html
{% extends 'templates/base.html' %}
{% block content %}
<title>Search</title>
<div class="search-container">
  <form action="{% url 'search' %}" method="post">
    {% csrf_token %}

    <label for="search">Search</label>
    <input type="text" id="search" name="search_query" placeholder="Find interesting article">

    <input class="registerbtn" type="submit" value="Find">

  </form>
<br>
<!--{% if search_result %}-->
<!--    {% for article in search_result %}-->
<!--    <a href="{{ article.get_absolute_url }}">{{ article.title }}</a>-->
<!--    {% endfor %}-->
<!--{% endif %}-->
{% if search_result %}
<ul class="latest_articles">
    {% for article in search_result %}
        <li style="margin-top: 20px; font-size: 20px"><a href="{{ article.get_absolute_url }}">{{ article.title }}</a></li>
        <p style="margin-top: 3px; margin-bottom: 0px;">Date: {{ article.time_create.date }}</p>
        <hr style="background-color: #6495ED; height: 2px; width: 100%; margin-left: 0px;">
    {% endfor %}

</ul>
{% endif %}
    {% if empty_result %}
    <p style="margin-top: 20px; font-size: 20px">Seems list is empty, try again... </p>
{% endif %}
</div>


{% endblock %}